package com.mwr.database;
// Generated 18 Oct 2013 10:19:39 PM by Hibernate Tools 3.2.1.GA



/**
 * Activeuser generated by hbm2java
 */
public class Activeuser  implements java.io.Serializable {


     private String ip;
     private String deviceMacaddress;
     private String deviceAndroidId;
     private String deviceSerialNumber;

    public Activeuser() {
    }

    public Activeuser(String ip, String deviceMacaddress, String deviceAndroidId, String deviceSerialNumber) {
       this.ip = ip;
       this.deviceMacaddress = deviceMacaddress;
       this.deviceAndroidId = deviceAndroidId;
       this.deviceSerialNumber = deviceSerialNumber;
    }
   
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getDeviceMacaddress() {
        return this.deviceMacaddress;
    }
    
    public void setDeviceMacaddress(String deviceMacaddress) {
        this.deviceMacaddress = deviceMacaddress;
    }
    public String getDeviceAndroidId() {
        return this.deviceAndroidId;
    }
    
    public void setDeviceAndroidId(String deviceAndroidId) {
        this.deviceAndroidId = deviceAndroidId;
    }
    public String getDeviceSerialNumber() {
        return this.deviceSerialNumber;
    }
    
    public void setDeviceSerialNumber(String deviceSerialNumber) {
        this.deviceSerialNumber = deviceSerialNumber;
    }




}


