package com.mwr.database;
// Generated 29-Aug-2013 18:05:58 by Hibernate Tools 3.2.1.GA



/**
 * DevicenotregisteredId generated by hbm2java
 */
public class DevicenotregisteredId  implements java.io.Serializable {


     private String macadress;
     private String androidId;
     private String serialNumber;

    public DevicenotregisteredId() {
    }

    public DevicenotregisteredId(String macadress, String androidId, String serialNumber) {
       this.macadress = macadress;
       this.androidId = androidId;
       this.serialNumber = serialNumber;
    }
   
    public String getMacadress() {
        return this.macadress;
    }
    
    public void setMacadress(String macadress) {
        this.macadress = macadress;
    }
    public String getAndroidId() {
        return this.androidId;
    }
    
    public void setAndroidId(String androidId) {
        this.androidId = androidId;
    }
    public String getSerialNumber() {
        return this.serialNumber;
    }
    
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DevicenotregisteredId) ) return false;
		 DevicenotregisteredId castOther = ( DevicenotregisteredId ) other; 
         
		 return ( (this.getMacadress()==castOther.getMacadress()) || ( this.getMacadress()!=null && castOther.getMacadress()!=null && this.getMacadress().equals(castOther.getMacadress()) ) )
 && ( (this.getAndroidId()==castOther.getAndroidId()) || ( this.getAndroidId()!=null && castOther.getAndroidId()!=null && this.getAndroidId().equals(castOther.getAndroidId()) ) )
 && ( (this.getSerialNumber()==castOther.getSerialNumber()) || ( this.getSerialNumber()!=null && castOther.getSerialNumber()!=null && this.getSerialNumber().equals(castOther.getSerialNumber()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMacadress() == null ? 0 : this.getMacadress().hashCode() );
         result = 37 * result + ( getAndroidId() == null ? 0 : this.getAndroidId().hashCode() );
         result = 37 * result + ( getSerialNumber() == null ? 0 : this.getSerialNumber().hashCode() );
         return result;
   }   


}


