package com.mwr.database;
// Generated 29-Aug-2013 18:05:58 by Hibernate Tools 3.2.1.GA



/**
 * DeviceId generated by hbm2java
 */
public class DeviceId  implements java.io.Serializable {


     private String macaddress;
     private String uid;
     private String serialNumber;

    public DeviceId() {
    }

    public DeviceId(String macaddress, String uid, String serialNumber) {
       this.macaddress = macaddress;
       this.uid = uid;
       this.serialNumber = serialNumber;
    }
   
    public String getMacaddress() {
        return this.macaddress;
    }
    
    public void setMacaddress(String macaddress) {
        this.macaddress = macaddress;
    }
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }
    public String getSerialNumber() {
        return this.serialNumber;
    }
    
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DeviceId) ) return false;
		 DeviceId castOther = ( DeviceId ) other; 
         
		 return ( (this.getMacaddress()==castOther.getMacaddress()) || ( this.getMacaddress()!=null && castOther.getMacaddress()!=null && this.getMacaddress().equals(castOther.getMacaddress()) ) )
 && ( (this.getUid()==castOther.getUid()) || ( this.getUid()!=null && castOther.getUid()!=null && this.getUid().equals(castOther.getUid()) ) )
 && ( (this.getSerialNumber()==castOther.getSerialNumber()) || ( this.getSerialNumber()!=null && castOther.getSerialNumber()!=null && this.getSerialNumber().equals(castOther.getSerialNumber()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMacaddress() == null ? 0 : this.getMacaddress().hashCode() );
         result = 37 * result + ( getUid() == null ? 0 : this.getUid().hashCode() );
         result = 37 * result + ( getSerialNumber() == null ? 0 : this.getSerialNumber().hashCode() );
         return result;
   }   


}


