package com.mwr.database;
// Generated 24 Sep 2013 1:24:20 PM by Hibernate Tools 3.2.1.GA



/**
 * DevicenotregisteredId generated by hbm2java
 */
public class DevicenotregisteredId  implements java.io.Serializable {


     private String macaddress;
     private String androidId;
     private String serialNumber;

    /**
     *
     */
    public DevicenotregisteredId() {
    }

    /**
     *
     * @param macaddress
     * @param androidId
     * @param serialNumber
     */
    public DevicenotregisteredId(String macaddress, String androidId, String serialNumber) {
       this.macaddress = macaddress;
       this.androidId = androidId;
       this.serialNumber = serialNumber;
    }
   
    /**
     *
     * @return
     */
    public String getMacaddress() {
        return this.macaddress;
    }
    
    /**
     *
     * @param macaddress
     */
    public void setMacaddress(String macaddress) {
        this.macaddress = macaddress;
    }
    /**
     *
     * @return
     */
    public String getAndroidId() {
        return this.androidId;
    }
    
    /**
     *
     * @param androidId
     */
    public void setAndroidId(String androidId) {
        this.androidId = androidId;
    }
    /**
     *
     * @return
     */
    public String getSerialNumber() {
        return this.serialNumber;
    }
    
    /**
     *
     * @param serialNumber
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DevicenotregisteredId) ) return false;
		 DevicenotregisteredId castOther = ( DevicenotregisteredId ) other; 
         
		 return ( (this.getMacaddress()==castOther.getMacaddress()) || ( this.getMacaddress()!=null && castOther.getMacaddress()!=null && this.getMacaddress().equals(castOther.getMacaddress()) ) )
 && ( (this.getAndroidId()==castOther.getAndroidId()) || ( this.getAndroidId()!=null && castOther.getAndroidId()!=null && this.getAndroidId().equals(castOther.getAndroidId()) ) )
 && ( (this.getSerialNumber()==castOther.getSerialNumber()) || ( this.getSerialNumber()!=null && castOther.getSerialNumber()!=null && this.getSerialNumber().equals(castOther.getSerialNumber()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMacaddress() == null ? 0 : this.getMacaddress().hashCode() );
         result = 37 * result + ( getAndroidId() == null ? 0 : this.getAndroidId().hashCode() );
         result = 37 * result + ( getSerialNumber() == null ? 0 : this.getSerialNumber().hashCode() );
         return result;
   }   


}


