package com.mwr.database;
// Generated 29-Aug-2013 18:05:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Device generated by hbm2java
 */
public class Device  implements java.io.Serializable {


     private DeviceId id;
     private Employee employee;
     private String make;
     private String model;
     private Date dateRegistered;

    public Device() {
    }

    public Device(DeviceId id, Employee employee, String make, String model, Date dateRegistered) {
       this.id = id;
       this.employee = employee;
       this.make = make;
       this.model = model;
       this.dateRegistered = dateRegistered;
    }
   
    public DeviceId getId() {
        return this.id;
    }
    
    public void setId(DeviceId id) {
        this.id = id;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getMake() {
        return this.make;
    }
    
    public void setMake(String make) {
        this.make = make;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public Date getDateRegistered() {
        return this.dateRegistered;
    }
    
    public void setDateRegistered(Date dateRegistered) {
        this.dateRegistered = dateRegistered;
    }




}


