package com.mwr.database;
// Generated 24 Sep 2013 1:24:20 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

    private Integer empId;
    private String username;
    private String password;
    private Date dateRegistered;
    private String name;
    private String surname;
    private String idnumber;
    private Set devices = new HashSet(0);

    public Employee() {
    }

    public Employee(String username, String password, Date dateRegistered, String name, String surname, String idnumber) {
        this.username = username;
        this.password = password;
        this.dateRegistered = dateRegistered;
        this.name = name;
        this.surname = surname;
        this.idnumber = idnumber;
    }

    public Employee(String username, String password, Date dateRegistered, String name, String surname, String idnumber, Set devices) {
        this.username = username;
        this.password = password;
        this.dateRegistered = dateRegistered;
        this.name = name;
        this.surname = surname;
        this.idnumber = idnumber;
        this.devices = devices;
    }

    public Integer getEmpId() {
        return this.empId;
    }

    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getDateRegistered() {
        String d = this.dateRegistered.toString();
        d = d.substring(0, d.length() - 2);
        int year = 0, month = 0, day = 0, hour = 0, minute = 0, second = 0;
        String date = d.substring(0, d.indexOf(" "));
        String time = d.substring(d.indexOf(" ") + 1);
        try {
            year = Integer.parseInt(date.split("-")[0]);
            month = Integer.parseInt(date.split("-")[1]);
            day = Integer.parseInt(date.split("-")[2]);
            hour = Integer.parseInt(time.split(":")[0]);
            minute = Integer.parseInt(time.split(":")[1]);
            second = Integer.parseInt(time.split(":")[2]);
        } finally {
            d = day + "/" + month + "/" + year + " " + hour + ":" + minute + ":" + second;
            return d;
        }
    }

    public void setDateRegistered(Date dateRegistered) {
        this.dateRegistered = dateRegistered;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getIdnumber() {
        return this.idnumber;
    }

    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber;
    }

    public Set getDevices() {
        return this.devices;
    }

    public void setDevices(Set devices) {
        this.devices = devices;
    }
}
