package com.mwr.database;
// Generated 29-Aug-2013 18:05:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer empId;
     private String username;
     private String password;
     private Date dateRegistered;
     private String name;
     private String surname;
     private String idnumber;
     private Set<Device> devices = new HashSet<Device>(0);

    public Employee() {
    }

	
    public Employee(String username, String password, Date dateRegistered, String name, String surname, String idnumber) {
        this.username = username;
        this.password = password;
        this.dateRegistered = dateRegistered;
        this.name = name;
        this.surname = surname;
        this.idnumber = idnumber;
    }
    public Employee(String username, String password, Date dateRegistered, String name, String surname, String idnumber, Set<Device> devices) {
       this.username = username;
       this.password = password;
       this.dateRegistered = dateRegistered;
       this.name = name;
       this.surname = surname;
       this.idnumber = idnumber;
       this.devices = devices;
    }
   
    public Integer getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getDateRegistered() {
        return this.dateRegistered;
    }
    
    public void setDateRegistered(Date dateRegistered) {
        this.dateRegistered = dateRegistered;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getIdnumber() {
        return this.idnumber;
    }
    
    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber;
    }
    public Set<Device> getDevices() {
        return this.devices;
    }
    
    public void setDevices(Set<Device> devices) {
        this.devices = devices;
    }




}


