package com.mwr.database;
// Generated 12 Sep 2013 10:55:53 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Scanresults generated by hbm2java
 */
public class Scanresults  implements java.io.Serializable {


     private int scanId;
     private Settings settings;
     private Date date;
     private boolean rooted;
     private int rootedScore;
     private boolean debuggingEnabled;
     private int debuggingEnabledScore;
     private boolean unknownSourcesAllowed;
     private int unknownSourcesScore;
     private String blacklistedApps;
     private int appsScore;
     private String osversion;
     private int osscore;
     private int totalScore;
     private boolean accessAllowed;
     private String deviceMacaddress;
     private String deviceUid;
     private String deviceSerialNumber;

    public Scanresults() {
    }

    public Scanresults(int scanId, Settings settings, Date date, boolean rooted, int rootedScore, boolean debuggingEnabled, int debuggingEnabledScore, boolean unknownSourcesAllowed, int unknownSourcesScore, String blacklistedApps, int appsScore, String osversion, int osscore, int totalScore, boolean accessAllowed, String deviceMacaddress, String deviceUid, String deviceSerialNumber) {
       this.scanId = scanId;
       this.settings = settings;
       this.date = date;
       this.rooted = rooted;
       this.rootedScore = rootedScore;
       this.debuggingEnabled = debuggingEnabled;
       this.debuggingEnabledScore = debuggingEnabledScore;
       this.unknownSourcesAllowed = unknownSourcesAllowed;
       this.unknownSourcesScore = unknownSourcesScore;
       this.blacklistedApps = blacklistedApps;
       this.appsScore = appsScore;
       this.osversion = osversion;
       this.osscore = osscore;
       this.totalScore = totalScore;
       this.accessAllowed = accessAllowed;
       this.deviceMacaddress = deviceMacaddress;
       this.deviceUid = deviceUid;
       this.deviceSerialNumber = deviceSerialNumber;
    }
    
    public Scanresults(Settings settings, Date date, boolean rooted, int rootedScore, boolean debuggingEnabled, int debuggingEnabledScore, boolean unknownSourcesAllowed, int unknownSourcesScore, String blacklistedApps, int appsScore, String osversion, int osscore, int totalScore, boolean accessAllowed, String deviceMacaddress, String deviceUid, String deviceSerialNumber) {
       this.settings = settings;
       this.date = date;
       this.rooted = rooted;
       this.rootedScore = rootedScore;
       this.debuggingEnabled = debuggingEnabled;
       this.debuggingEnabledScore = debuggingEnabledScore;
       this.unknownSourcesAllowed = unknownSourcesAllowed;
       this.unknownSourcesScore = unknownSourcesScore;
       this.blacklistedApps = blacklistedApps;
       this.appsScore = appsScore;
       this.osversion = osversion;
       this.osscore = osscore;
       this.totalScore = totalScore;
       this.accessAllowed = accessAllowed;
       this.deviceMacaddress = deviceMacaddress;
       this.deviceUid = deviceUid;
       this.deviceSerialNumber = deviceSerialNumber;
    }
   
    public int getScanId() {
        return this.scanId;
    }
    
    public void setScanId(int scanId) {
        this.scanId = scanId;
    }
    public Settings getSettings() {
        return this.settings;
    }
    
    public void setSettings(Settings settings) {
        this.settings = settings;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public boolean isRooted() {
        return this.rooted;
    }
    
    public void setRooted(boolean rooted) {
        this.rooted = rooted;
    }
    public int getRootedScore() {
        return this.rootedScore;
    }
    
    public void setRootedScore(int rootedScore) {
        this.rootedScore = rootedScore;
    }
    public boolean isDebuggingEnabled() {
        return this.debuggingEnabled;
    }
    
    public void setDebuggingEnabled(boolean debuggingEnabled) {
        this.debuggingEnabled = debuggingEnabled;
    }
    public int getDebuggingEnabledScore() {
        return this.debuggingEnabledScore;
    }
    
    public void setDebuggingEnabledScore(int debuggingEnabledScore) {
        this.debuggingEnabledScore = debuggingEnabledScore;
    }
    public boolean isUnknownSourcesAllowed() {
        return this.unknownSourcesAllowed;
    }
    
    public void setUnknownSourcesAllowed(boolean unknownSourcesAllowed) {
        this.unknownSourcesAllowed = unknownSourcesAllowed;
    }
    public int getUnknownSourcesScore() {
        return this.unknownSourcesScore;
    }
    
    public void setUnknownSourcesScore(int unknownSourcesScore) {
        this.unknownSourcesScore = unknownSourcesScore;
    }
    public String getBlacklistedApps() {
        return this.blacklistedApps;
    }
    
    public void setBlacklistedApps(String blacklistedApps) {
        this.blacklistedApps = blacklistedApps;
    }
    public int getAppsScore() {
        return this.appsScore;
    }
    
    public void setAppsScore(int appsScore) {
        this.appsScore = appsScore;
    }
    public String getOsversion() {
        return this.osversion;
    }
    
    public void setOsversion(String osversion) {
        this.osversion = osversion;
    }
    public int getOsscore() {
        return this.osscore;
    }
    
    public void setOsscore(int osscore) {
        this.osscore = osscore;
    }
    public int getTotalScore() {
        return this.totalScore;
    }
    
    public void setTotalScore(int totalScore) {
        this.totalScore = totalScore;
    }
    public boolean isAccessAllowed() {
        return this.accessAllowed;
    }
    
    public void setAccessAllowed(boolean accessAllowed) {
        this.accessAllowed = accessAllowed;
    }
    public String getDeviceMacaddress() {
        return this.deviceMacaddress;
    }
    
    public void setDeviceMacaddress(String deviceMacaddress) {
        this.deviceMacaddress = deviceMacaddress;
    }
    public String getDeviceUid() {
        return this.deviceUid;
    }
    
    public void setDeviceUid(String deviceUid) {
        this.deviceUid = deviceUid;
    }
    public String getDeviceSerialNumber() {
        return this.deviceSerialNumber;
    }
    
    public void setDeviceSerialNumber(String deviceSerialNumber) {
        this.deviceSerialNumber = deviceSerialNumber;
    }




}


