package com.mwr.database;
// Generated 23 Sep 2013 5:37:49 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Scanresult generated by hbm2java
 */
public class Scanresult  implements java.io.Serializable {


     private Integer scanId;
     private Device device;
     private Setting setting;
     private Date date;
     private boolean rooted;
     private int rootedScore;
     private boolean debuggingEnabled;
     private int debuggingEnabledScore;
     private boolean unknownSourcesAllowed;
     private int unknownSourcesScore;
     private String blacklistedApps;
     private int appsScore;
     private String osversion;
     private int osscore;
     private int totalScore;
     private boolean accessAllowed;

    public Scanresult() {
    }

    public Scanresult(Device device, Setting setting, Date date, boolean rooted, int rootedScore, boolean debuggingEnabled, int debuggingEnabledScore, boolean unknownSourcesAllowed, int unknownSourcesScore, String blacklistedApps, int appsScore, String osversion, int osscore, int totalScore, boolean accessAllowed) {
       this.device = device;
       this.setting = setting;
       this.date = date;
       this.rooted = rooted;
       this.rootedScore = rootedScore;
       this.debuggingEnabled = debuggingEnabled;
       this.debuggingEnabledScore = debuggingEnabledScore;
       this.unknownSourcesAllowed = unknownSourcesAllowed;
       this.unknownSourcesScore = unknownSourcesScore;
       this.blacklistedApps = blacklistedApps;
       this.appsScore = appsScore;
       this.osversion = osversion;
       this.osscore = osscore;
       this.totalScore = totalScore;
       this.accessAllowed = accessAllowed;
    }
   
    public Integer getScanId() {
        return this.scanId;
    }
    
    public void setScanId(Integer scanId) {
        this.scanId = scanId;
    }
    public Device getDevice() {
        return this.device;
    }
    
    public void setDevice(Device device) {
        this.device = device;
    }
    public Setting getSetting() {
        return this.setting;
    }
    
    public void setSetting(Setting setting) {
        this.setting = setting;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public boolean isRooted() {
        return this.rooted;
    }
    
    public void setRooted(boolean rooted) {
        this.rooted = rooted;
    }
    public int getRootedScore() {
        return this.rootedScore;
    }
    
    public void setRootedScore(int rootedScore) {
        this.rootedScore = rootedScore;
    }
    public boolean isDebuggingEnabled() {
        return this.debuggingEnabled;
    }
    
    public void setDebuggingEnabled(boolean debuggingEnabled) {
        this.debuggingEnabled = debuggingEnabled;
    }
    public int getDebuggingEnabledScore() {
        return this.debuggingEnabledScore;
    }
    
    public void setDebuggingEnabledScore(int debuggingEnabledScore) {
        this.debuggingEnabledScore = debuggingEnabledScore;
    }
    public boolean isUnknownSourcesAllowed() {
        return this.unknownSourcesAllowed;
    }
    
    public void setUnknownSourcesAllowed(boolean unknownSourcesAllowed) {
        this.unknownSourcesAllowed = unknownSourcesAllowed;
    }
    public int getUnknownSourcesScore() {
        return this.unknownSourcesScore;
    }
    
    public void setUnknownSourcesScore(int unknownSourcesScore) {
        this.unknownSourcesScore = unknownSourcesScore;
    }
    public String getBlacklistedApps() {
        return this.blacklistedApps;
    }
    
    public void setBlacklistedApps(String blacklistedApps) {
        this.blacklistedApps = blacklistedApps;
    }
    public int getAppsScore() {
        return this.appsScore;
    }
    
    public void setAppsScore(int appsScore) {
        this.appsScore = appsScore;
    }
    public String getOsversion() {
        return this.osversion;
    }
    
    public void setOsversion(String osversion) {
        this.osversion = osversion;
    }
    public int getOsscore() {
        return this.osscore;
    }
    
    public void setOsscore(int osscore) {
        this.osscore = osscore;
    }
    public int getTotalScore() {
        return this.totalScore;
    }
    
    public void setTotalScore(int totalScore) {
        this.totalScore = totalScore;
    }
    public boolean isAccessAllowed() {
        return this.accessAllowed;
    }
    
    public void setAccessAllowed(boolean accessAllowed) {
        this.accessAllowed = accessAllowed;
    }




}


