package com.mwr.database;
// Generated 23 Sep 2013 5:48:30 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Setting generated by hbm2java
 */
public class Setting  implements java.io.Serializable {


     private Integer settingId;
     private int accessScore;
     private Date settingDate;
     private int osweight;
     private int rootedWeight;
     private int debugWeight;
     private int unknownSourcesWeight;
     private int lowRiskApp;
     private int mediumRiskApp;
     private int highRiskApp;
     private int blockedApp;

    public Setting() {
    }

    public Setting(int accessScore, Date settingDate, int osweight, int rootedWeight, int debugWeight, int unknownSourcesWeight, int lowRiskApp, int mediumRiskApp, int highRiskApp, int blockedApp) {
       this.accessScore = accessScore;
       this.settingDate = settingDate;
       this.osweight = osweight;
       this.rootedWeight = rootedWeight;
       this.debugWeight = debugWeight;
       this.unknownSourcesWeight = unknownSourcesWeight;
       this.lowRiskApp = lowRiskApp;
       this.mediumRiskApp = mediumRiskApp;
       this.highRiskApp = highRiskApp;
       this.blockedApp = blockedApp;
    }
   
    public Integer getSettingId() {
        return this.settingId;
    }
    
    public void setSettingId(Integer settingId) {
        this.settingId = settingId;
    }
    public int getAccessScore() {
        return this.accessScore;
    }
    
    public void setAccessScore(int accessScore) {
        this.accessScore = accessScore;
    }
    public Date getSettingDate() {
        return this.settingDate;
    }
    
    public void setSettingDate(Date settingDate) {
        this.settingDate = settingDate;
    }
    public int getOsweight() {
        return this.osweight;
    }
    
    public void setOsweight(int osweight) {
        this.osweight = osweight;
    }
    public int getRootedWeight() {
        return this.rootedWeight;
    }
    
    public void setRootedWeight(int rootedWeight) {
        this.rootedWeight = rootedWeight;
    }
    public int getDebugWeight() {
        return this.debugWeight;
    }
    
    public void setDebugWeight(int debugWeight) {
        this.debugWeight = debugWeight;
    }
    public int getUnknownSourcesWeight() {
        return this.unknownSourcesWeight;
    }
    
    public void setUnknownSourcesWeight(int unknownSourcesWeight) {
        this.unknownSourcesWeight = unknownSourcesWeight;
    }
    public int getLowRiskApp() {
        return this.lowRiskApp;
    }
    
    public void setLowRiskApp(int lowRiskApp) {
        this.lowRiskApp = lowRiskApp;
    }
    public int getMediumRiskApp() {
        return this.mediumRiskApp;
    }
    
    public void setMediumRiskApp(int mediumRiskApp) {
        this.mediumRiskApp = mediumRiskApp;
    }
    public int getHighRiskApp() {
        return this.highRiskApp;
    }
    
    public void setHighRiskApp(int highRiskApp) {
        this.highRiskApp = highRiskApp;
    }
    public int getBlockedApp() {
        return this.blockedApp;
    }
    
    public void setBlockedApp(int blockedApp) {
        this.blockedApp = blockedApp;
    }




}


