package com.mwr.database;
// Generated 24 Sep 2013 1:24:20 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Setting generated by hbm2java
 */
public class Setting implements java.io.Serializable {

    private Integer settingId;
    private int accessScore;
    private Date settingDate;
    private int apiweight;
    private int rootedWeight;
    private int debugWeight;
    private int unknownSourcesWeight;
    private int lowRiskApp;
    private int mediumRiskApp;
    private int highRiskApp;
    private int blockedApp;
    private Set scanresults = new HashSet(0);

    public Setting() {
    }

    public Setting(int accessScore, Date settingDate, int apiweight, int rootedWeight, int debugWeight, int unknownSourcesWeight, int lowRiskApp, int mediumRiskApp, int highRiskApp, int blockedApp) {
        this.accessScore = accessScore;
        this.settingDate = settingDate;
        this.apiweight = apiweight;
        this.rootedWeight = rootedWeight;
        this.debugWeight = debugWeight;
        this.unknownSourcesWeight = unknownSourcesWeight;
        this.lowRiskApp = lowRiskApp;
        this.mediumRiskApp = mediumRiskApp;
        this.highRiskApp = highRiskApp;
        this.blockedApp = blockedApp;
    }

    public Setting(int accessScore, Date settingDate, int apiweight, int rootedWeight, int debugWeight, int unknownSourcesWeight, int lowRiskApp, int mediumRiskApp, int highRiskApp, int blockedApp, Set scanresults) {
        this.accessScore = accessScore;
        this.settingDate = settingDate;
        this.apiweight = apiweight;
        this.rootedWeight = rootedWeight;
        this.debugWeight = debugWeight;
        this.unknownSourcesWeight = unknownSourcesWeight;
        this.lowRiskApp = lowRiskApp;
        this.mediumRiskApp = mediumRiskApp;
        this.highRiskApp = highRiskApp;
        this.blockedApp = blockedApp;
        this.scanresults = scanresults;
    }

    public Integer getSettingId() {
        return this.settingId;
    }

    public void setSettingId(Integer settingId) {
        this.settingId = settingId;
    }

    public int getAccessScore() {
        return this.accessScore;
    }

    public void setAccessScore(int accessScore) {
        this.accessScore = accessScore;
    }

    public String getSettingDate() {
        String d = this.settingDate.toString();
        d = d.substring(0, d.length() - 2);
        int year = 0, month = 0, day = 0, hour = 0, minute = 0, second = 0;
        String date = d.substring(0, d.indexOf(" "));
        String time = d.substring(d.indexOf(" ") + 1);
        try {
            year = Integer.parseInt(date.split("-")[0]);
            month = Integer.parseInt(date.split("-")[1]);
            day = Integer.parseInt(date.split("-")[2]);
            hour = Integer.parseInt(time.split(":")[0]);
            minute = Integer.parseInt(time.split(":")[1]);
            second = Integer.parseInt(time.split(":")[2]);
        } finally {
            d = day + "/" + month + "/" + year + " " + hour + "h" + minute + "m" + second + "s";
            return d;
        }
    }

    public void setSettingDate(Date settingDate) {
        this.settingDate = settingDate;
    }

    public int getApiweight() {
        return this.apiweight;
    }

    public void setApiweight(int apiweight) {
        this.apiweight = apiweight;
    }

    public int getRootedWeight() {
        return this.rootedWeight;
    }

    public void setRootedWeight(int rootedWeight) {
        this.rootedWeight = rootedWeight;
    }

    public int getDebugWeight() {
        return this.debugWeight;
    }

    public void setDebugWeight(int debugWeight) {
        this.debugWeight = debugWeight;
    }

    public int getUnknownSourcesWeight() {
        return this.unknownSourcesWeight;
    }

    public void setUnknownSourcesWeight(int unknownSourcesWeight) {
        this.unknownSourcesWeight = unknownSourcesWeight;
    }

    public int getLowRiskApp() {
        return this.lowRiskApp;
    }

    public void setLowRiskApp(int lowRiskApp) {
        this.lowRiskApp = lowRiskApp;
    }

    public int getMediumRiskApp() {
        return this.mediumRiskApp;
    }

    public void setMediumRiskApp(int mediumRiskApp) {
        this.mediumRiskApp = mediumRiskApp;
    }

    public int getHighRiskApp() {
        return this.highRiskApp;
    }

    public void setHighRiskApp(int highRiskApp) {
        this.highRiskApp = highRiskApp;
    }

    public int getBlockedApp() {
        return this.blockedApp;
    }

    public void setBlockedApp(int blockedApp) {
        this.blockedApp = blockedApp;
    }

    public Set getScanresults() {
        return this.scanresults;
    }

    public void setScanresults(Set scanresults) {
        this.scanresults = scanresults;
    }
}
