package com.mwr.database;
// Generated 12 Sep 2013 11:46:09 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Settings generated by hbm2java
 */
public class Settings  implements java.io.Serializable {


     private Integer settingId;
     private Integer accessScore;
     private Date settingDate;
     private int osweight;
     private int rootedWeight;
     private int debugWeight;
     private int unknownSourcesWeight;
     private int lowRiskApp;
     private int mediumRiskApp;
     private int highRiskApp;
     private int blockedApp;
     private Set scanresultses = new HashSet(0);

    public Settings() {
    }

	
    public Settings(Integer access, int osweight, int rootedWeight, int debugWeight, int unknownSourcesWeight, int lowRiskApp, int mediumRiskApp, int highRiskApp, int blockedApp) {
        this.settingDate = new Date();
        this.osweight = osweight;
        this.rootedWeight = rootedWeight;
        this.debugWeight = debugWeight;
        this.unknownSourcesWeight = unknownSourcesWeight;
        this.lowRiskApp = lowRiskApp;
        this.mediumRiskApp = mediumRiskApp;
        this.highRiskApp = highRiskApp;
        this.blockedApp = blockedApp;
        this.accessScore = access;
    }
    public Settings(Integer accessScore, Date settingDate, int osweight, int rootedWeight, int debugWeight, int unknownSourcesWeight, int lowRiskApp, int mediumRiskApp, int highRiskApp, int blockedApp, Set scanresultses) {
       this.accessScore = accessScore;
       this.settingDate = settingDate;
       this.osweight = osweight;
       this.rootedWeight = rootedWeight;
       this.debugWeight = debugWeight;
       this.unknownSourcesWeight = unknownSourcesWeight;
       this.lowRiskApp = lowRiskApp;
       this.mediumRiskApp = mediumRiskApp;
       this.highRiskApp = highRiskApp;
       this.blockedApp = blockedApp;
       this.scanresultses = scanresultses;
    }
   
    public Integer getSettingId() {
        return this.settingId;
    }
    
    public void setSettingId(Integer settingId) {
        this.settingId = settingId;
    }
    public Integer getAccessScore() {
        return this.accessScore;
    }
    
    public void setAccessScore(Integer accessScore) {
        this.accessScore = accessScore;
    }
    public Date getSettingDate() {
        return this.settingDate;
    }
    
    public void setSettingDate(Date settingDate) {
        this.settingDate = settingDate;
    }
    public int getOsweight() {
        return this.osweight;
    }
    
    public void setOsweight(int osweight) {
        this.osweight = osweight;
    }
    public int getRootedWeight() {
        return this.rootedWeight;
    }
    
    public void setRootedWeight(int rootedWeight) {
        this.rootedWeight = rootedWeight;
    }
    public int getDebugWeight() {
        return this.debugWeight;
    }
    
    public void setDebugWeight(int debugWeight) {
        this.debugWeight = debugWeight;
    }
    public int getUnknownSourcesWeight() {
        return this.unknownSourcesWeight;
    }
    
    public void setUnknownSourcesWeight(int unknownSourcesWeight) {
        this.unknownSourcesWeight = unknownSourcesWeight;
    }
    public int getLowRiskApp() {
        return this.lowRiskApp;
    }
    
    public void setLowRiskApp(int lowRiskApp) {
        this.lowRiskApp = lowRiskApp;
    }
    public int getMediumRiskApp() {
        return this.mediumRiskApp;
    }
    
    public void setMediumRiskApp(int mediumRiskApp) {
        this.mediumRiskApp = mediumRiskApp;
    }
    public int getHighRiskApp() {
        return this.highRiskApp;
    }
    
    public void setHighRiskApp(int highRiskApp) {
        this.highRiskApp = highRiskApp;
    }
    public int getBlockedApp() {
        return this.blockedApp;
    }
    
    public void setBlockedApp(int blockedApp) {
        this.blockedApp = blockedApp;
    }
    public Set getScanresultses() {
        return this.scanresultses;
    }
    
    public void setScanresultses(Set scanresultses) {
        this.scanresultses = scanresultses;
    }




}


