package com.mwr.database;
// Generated 29-Aug-2013 18:05:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Technician generated by hbm2java
 */
public class Technician  implements java.io.Serializable {


     private Integer technicianId;
     private String employeeCode;
     private String userName;
     private String password;
     private byte[] photo;
     private Date dateRegistered;
     private boolean admin;

    public Technician() {
    }

	
    public Technician(String employeeCode, String userName, String password, Date dateRegistered, boolean admin) {
        this.employeeCode = employeeCode;
        this.userName = userName;
        this.password = password;
        this.dateRegistered = dateRegistered;
        this.admin = admin;
    }
    public Technician(String employeeCode, String userName, String password, byte[] photo, Date dateRegistered, boolean admin) {
       this.employeeCode = employeeCode;
       this.userName = userName;
       this.password = password;
       this.photo = photo;
       this.dateRegistered = dateRegistered;
       this.admin = admin;
    }
   
    public Integer getTechnicianId() {
        return this.technicianId;
    }
    
    public void setTechnicianId(Integer technicianId) {
        this.technicianId = technicianId;
    }
    public String getEmployeeCode() {
        return this.employeeCode;
    }
    
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    public Date getDateRegistered() {
        return this.dateRegistered;
    }
    
    public void setDateRegistered(Date dateRegistered) {
        this.dateRegistered = dateRegistered;
    }
    public boolean isAdmin() {
        return this.admin;
    }
    
    public void setAdmin(boolean admin) {
        this.admin = admin;
    }




}


