package com.mwr.database;
// Generated 18 Oct 2013 10:19:39 PM by Hibernate Tools 3.2.1.GA



/**
 * Activeuser generated by hbm2java
 */
public class Activeuser  implements java.io.Serializable {


     private String ip;
     private String deviceMacaddress;
     private String deviceAndroidId;
     private String deviceSerialNumber;

    /**
     *
     */
    public Activeuser() {
    }

    /**
     *
     * @param ip
     * @param deviceMacaddress
     * @param deviceAndroidId
     * @param deviceSerialNumber
     */
    public Activeuser(String ip, String deviceMacaddress, String deviceAndroidId, String deviceSerialNumber) {
       this.ip = ip;
       this.deviceMacaddress = deviceMacaddress;
       this.deviceAndroidId = deviceAndroidId;
       this.deviceSerialNumber = deviceSerialNumber;
    }
   
    /**
     *
     * @return
     */
    public String getIp() {
        return this.ip;
    }
    
    /**
     *
     * @param ip
     */
    public void setIp(String ip) {
        this.ip = ip;
    }
    /**
     *
     * @return
     */
    public String getDeviceMacaddress() {
        return this.deviceMacaddress;
    }
    
    /**
     *
     * @param deviceMacaddress
     */
    public void setDeviceMacaddress(String deviceMacaddress) {
        this.deviceMacaddress = deviceMacaddress;
    }
    /**
     *
     * @return
     */
    public String getDeviceAndroidId() {
        return this.deviceAndroidId;
    }
    
    /**
     *
     * @param deviceAndroidId
     */
    public void setDeviceAndroidId(String deviceAndroidId) {
        this.deviceAndroidId = deviceAndroidId;
    }
    /**
     *
     * @return
     */
    public String getDeviceSerialNumber() {
        return this.deviceSerialNumber;
    }
    
    /**
     *
     * @param deviceSerialNumber
     */
    public void setDeviceSerialNumber(String deviceSerialNumber) {
        this.deviceSerialNumber = deviceSerialNumber;
    }




}


