package com.mwr.database;
// Generated 24 Oct 2013 4:17:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Activeuser generated by hbm2java
 */
public class Activeuser  implements java.io.Serializable {


     private String ip;
     private String deviceMacaddress;
     private String deviceAndroidId;
     private String deviceSerialNumber;
     private Date lastInteraction;

    public Activeuser() {
    }

    public Activeuser(String ip, String deviceMacaddress, String deviceAndroidId, String deviceSerialNumber, Date lastInteraction) {
       this.ip = ip;
       this.deviceMacaddress = deviceMacaddress;
       this.deviceAndroidId = deviceAndroidId;
       this.deviceSerialNumber = deviceSerialNumber;
       this.lastInteraction = lastInteraction;
    }
   
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getDeviceMacaddress() {
        return this.deviceMacaddress;
    }
    
    public void setDeviceMacaddress(String deviceMacaddress) {
        this.deviceMacaddress = deviceMacaddress;
    }
    public String getDeviceAndroidId() {
        return this.deviceAndroidId;
    }
    
    public void setDeviceAndroidId(String deviceAndroidId) {
        this.deviceAndroidId = deviceAndroidId;
    }
    public String getDeviceSerialNumber() {
        return this.deviceSerialNumber;
    }
    
    public void setDeviceSerialNumber(String deviceSerialNumber) {
        this.deviceSerialNumber = deviceSerialNumber;
    }
    public Date getLastInteraction() {
        return this.lastInteraction;
    }
    
    public void setLastInteraction(Date lastInteraction) {
        this.lastInteraction = lastInteraction;
    }




}


