package com.mwr.database;
// Generated 24 Sep 2013 1:24:20 PM by Hibernate Tools 3.2.1.GA



/**
 * Blacklistedapp generated by hbm2java
 */
public class Blacklistedapp  implements java.io.Serializable {


     private Integer appId;
     private String appName;
     private String appCategory;

    /**
     *
     */
    public Blacklistedapp() {
    }

    /**
     *
     * @param appName
     * @param appCategory
     */
    public Blacklistedapp(String appName, String appCategory) {
       this.appName = appName;
       this.appCategory = appCategory;
    }
   
    /**
     *
     * @return
     */
    public Integer getAppId() {
        return this.appId;
    }
    
    /**
     *
     * @param appId
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }
    /**
     *
     * @return
     */
    public String getAppName() {
        return this.appName;
    }
    
    /**
     *
     * @param appName
     */
    public void setAppName(String appName) {
        this.appName = appName;
    }
    /**
     *
     * @return
     */
    public String getAppCategory() {
        return this.appCategory;
    }
    
    /**
     *
     * @param appCategory
     */
    public void setAppCategory(String appCategory) {
        this.appCategory = appCategory;
    }




}


